pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success:
        - "Scala 2.12.12, Java adopt@1.8"
        - "Scala 2.13.3, Java adopt@1.8"
        - "Scala 2.12.12, Java adopt@1.11"
        - "Scala 2.13.3, Java adopt@1.11"
        - "Scala 2.12.12, Java adopt@1.14"
        - "Scala 2.13.3, Java adopt@1.14"
        - "Doc Site"
      - body~=labels:.*semver-patch.*
    actions:
      merge:
        method: merge
