name: cats-time
baseurl: /cats-time
description: Cats Typeclasses for Java Time
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.1+2-a7a79cfe-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
